dnl Process this file with autoconf to produce a configure script.
AC_INIT(bbmail.cc)

AM_INIT_AUTOMAKE(bbpager, 0.4.0)

AC_PREFIX_DEFAULT(/usr/local)

dnl get the debug values right
AC_DEFUN(AC_SET_DEBUG,
[
 test "$CXXFLAGS" = "" && CXXFLAGS="-g -Wall -DDEBUG"
 test "$LDFLAGS" = "" && LDFLAGS=""
])

AC_DEFUN(AC_SET_NODEBUG,
[
 test "$CXXFLAGS" = "" && CXXFLAGS="-O2 -Wall"
 test "$LDFLAGS" = "" && LDFLAGS="-s"
])
      

AC_ARG_ENABLE(debug,[  --enable-debug	create debugging code [default=no]],
[
if test $enableval = "no";
 then AC_SET_NODEBUG
 else AC_SET_DEBUG
fi
],
AC_SET_NODEBUG)

dnl Checks for programs.
dnl needed by configure itsself
AC_PROG_CC
AC_PROG_CXX
AC_PROG_CPP
AC_PROG_INSTALL

AC_HEADER_STDC
AC_CHECK_HEADERS(ctype.h fcntl.h libgen.h locale.h process.h signal.h stdio.h time.h unistd.h sys/param.h sys/select.h sys/stat.h sys/time.h sys/types.h sys/wait.h)
AC_HEADER_TIME

AC_CHECK_FUNCS(setlocale sigaction strftime)

AC_PATH_X
AC_PATH_XTRA

CFLAGS="$CFLAGS $X_CFLAGS"
CXXFLAGS="$CXXFLAGS $X_CFLAGS"
LDFLAGS="$LDFLAGS $X_LIBS $X_PRE_LIBS"
dnl Checks for X libraries.
AC_CHECK_LIB(X11, XOpenDisplay, LDFLAGS="$LDFLAGS -lX11",
             AC_MSG_ERROR(XOpenDisplay not found in -lX11))

dnl Checks for Xextension
SHAPE=
AC_CHECK_LIB(Xext, XMissingExtension, LIBS="$LIBS -lXext"; SHAPE="-DSHAPE",
             AC_MSG_ERROR(XMissingExtension not found in -lXext))
AC_SUBST(SHAPE)

dnl Checks for typedefs, structures, and compiler characteristics.
AC_C_CONST
AC_HEADER_TIME
AC_STRUCT_TM

dnl Checks for library functions.
AC_CHECK_FUNCS(select strstr)


dnl check for blackbox headers
blackbox_inc=""
AC_MSG_CHECKING([for blackbox headers])
AC_ARG_WITH(bt-includes,
        AC_HELP_STRING([--with-bt-includes], [blackbox library headers]),
        ac_blackbox_inc=$withval, ac_blackbox_inc="")

# if the blackbox headers directory was specified, make sure we have it
for btdir in $ac_blackbox_inc /usr/local /usr/lib /usr; do
    if test -f "$btdir/Application.hh"; then
       blackbox_inc=$btdir
       break
    fi
done

if test -z "$blackbox_inc"; then
   AC_MSG_RESULT([Not found])
   echo 
   echo "Couldn't find your blackbox library headers."
   echo "Use --with-bt-includes=dir option to fix this."
   echo 
   exit 1
fi

AC_MSG_RESULT([$blackbox_inc])
CXXFLAGS="$CXXFLAGS -I$blackbox_inc"


dnl now check for blackbox library
blackbox_lib=""
AC_MSG_CHECKING([for blackbox lib])
AC_ARG_WITH(bt-lib,
        AC_HELP_STRING([--with-bt-lib], [blackbox library]),
        ac_blackbox_lib=$withval, ac_blackbox_lib="")

# if the blackbox headers directory was specified, make sure we have it
for btdir in $ac_blackbox_lib /usr/local /usr/lib /usr; do
    if test -f "$btdir/libbt.a"; then
       blackbox_lib=$btdir
       break
    fi
done

if test -z "$blackbox_lib"; then
   AC_MSG_RESULT([Not found])
   echo 
   echo "Couldn't find your blackbox library."
   echo "Use --with-bt-lib=dir option to fix this."
   echo 
   exit 1
fi

AC_MSG_RESULT([$blackbox_lib])
LIBS="$LIBS -L$blackbox_lib -lbt"

dnl generate the config header
AM_CONFIG_HEADER(config.h) 

dnl Print results
AC_MSG_RESULT([])
AC_MSG_RESULT([	$PACKAGE version $VERSION configured successfully.])
AC_MSG_RESULT([])
AC_MSG_RESULT([Using '$prefix' for installation.])
AC_MSG_RESULT([Using '$CXX' for C++ compiler.])
AC_MSG_RESULT([Building with '$CXXFLAGS' for C++ compiler flags.])
AC_MSG_RESULT([Building with '$LIBS' for linker flags.])
AC_MSG_RESULT([])

AC_OUTPUT(Makefile data/Makefile scripts/Makefile)
